Add fuzzing support in devtool
Signed-off-by: George Mocanu <mocanu.geo98@gmail.com>

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -73,7 +73,7 @@
 # Development container image (name:tag)
 # This should be updated whenever we upgrade the development container.
 # (Yet another step on our way to reproducible builds.)
-DEVCTR_IMAGE="fcuvm/dev:v16"
+DEVCTR_IMAGE="fcuvm/dev:latest"
 
 # Naming things is hard
 MY_NAME="Firecracker $(basename "$0")"
@@ -86,6 +86,15 @@ FC_ROOT_DIR=$(cd "${FC_TOOLS_DIR}/.." && pwd)
 
 # Full path to the build dir on the host.
 FC_BUILD_DIR="${FC_ROOT_DIR}/build"
+
+# Full path to the fuzz output dir on the host.
+FC_FUZZ_OUTPUT_DIR="${FC_ROOT_DIR}/fuzz/out"
+
+# Full path to the fuzz coverage dir on the host.
+FC_FUZZ_COVERAGE_DIR="${FC_FUZZ_OUTPUT_DIR}/kcov-report"
+
+# Full path to the fuzzer dictionaries dir on the host.
+FC_FUZZ_DICTIONARIES_DIR="${FC_ROOT_DIR}/fuzz/dictionaries"
 
 # Full path to the cargo registry dir on the host. This appears on the host
 # because we want to persist the cargo registry across container invocations.
@@ -113,6 +122,18 @@ CTR_CARGO_TARGET_DIR="$CTR_FC_BUILD_DIR/cargo_target"
 
 # Full path to the microVM images cache dir
 CTR_MICROVM_IMAGES_DIR="$CTR_FC_BUILD_DIR/img"
+
+# Full path to the fuzz input dir, as bind-mounted in the container.
+CTR_FUZZ_INPUT_DIR="${CTR_FC_ROOT_DIR}/fuzz/in"
+
+# Full path to the fuzz output dir, as bind-mounted in the container.
+CTR_FUZZ_OUTPUT_DIR="${CTR_FC_ROOT_DIR}/fuzz/out"
+
+# Full path to the fuzz coverage dir, as bind-mounted in the container.
+CTR_FUZZ_COVERAGE_DIR="${CTR_FUZZ_OUTPUT_DIR}/kcov-report"
+
+# Full path to the fuzzer dictionaries dir, as bind-mounted in the container.
+CTR_FUZZ_DICTIONARIES_DIR="${CTR_FC_ROOT_DIR}/fuzz/dictionaries"
 
 # Global options received by $0
 # These options are not command-specific, so we store them as global vars
@@ -247,6 +268,23 @@ cmd_fix_perms() {
         chown -R "$(id -u):$(id -g)" "$CTR_FC_BUILD_DIR"
 }
 
+# Fix fuzzing out/ dir permissions after a privileged container run.
+# Since the privileged cotainer runs as root, any files it creates will be
+# owned by root. This fixes that by recursively changing the ownership of out/
+# to the current user.
+#
+fix_fuzz_dir_perms() {
+    run_devctr \
+        -- \
+        chown -R "$(id -u):$(id -g)" "$CTR_FUZZ_OUTPUT_DIR"
+}
+
+fix_cov_dir_perms() {
+    run_devctr \
+        -- \
+        chown -R "$(id -u):$(id -g)" "$CTR_FUZZ_COVERAGE_DIR"
+}
+
 # Prompt the user for confirmation before proceeding.
 # Args:
 #   $1  prompt text.
@@ -320,6 +358,114 @@ compose_tag_text() {
       | sed "s/^###\s//g"
 }
 
+# Run afl-tmin on multiple cores.
+# Args:
+#   $1  the number of cores to run afl-tmin on.
+#   $2  path to the AFL generated corpus.
+#   $3  path to the output directory for minimized corpus.
+#   $4  path to the fuzzed binary
+afl_ptmin() {
+    local cores="$1"
+    local inputdir="$2"
+    local outputdir="$3"
+    local fuzz_target="$4"
+
+    total=`ls $inputdir | wc -l`
+    [[ $total -eq "0" ]] && return
+
+    for k in $(seq 1 $cores $total); do
+        for i in $(seq 0 $(expr $cores - 1)); do
+            file=`ls -Sr $inputdir | sed $(expr $i + $k)"q;d"`
+            cargo afl tmin \
+                -i "$inputdir/$file" \
+                -o "$outputdir/$file.min" \
+                -m 512 \
+                -e \
+                -- \
+                ./"$fuzz_target"
+        done
+
+        wait
+    done
+}
+
+# Minimize the fuzz output generated by AFL, using afl-cmin and afl-tmin
+# tools. Because afl-tmin is time consuming, use a parallel version of it.
+# Args:
+#   $1  the number of cores to run afl-tmin on.
+#   $2  path to the fuzzed binary.
+#   $3  path to the AFL output dir.
+minimize_afl_output() {
+    local cores="$1"
+    local fuzz_target="$2"
+    local outputdir="$3"
+
+    local all_queues_dir="$outputdir/all_queues"
+    local all_crashes_dir="$outputdir/all_crashes"
+    local cmin_queue_dir="$outputdir/cmin_queue"
+    local cmin_crashes_dir="$outputdir/cmin_crashes"
+    local tmin_queue_dir="$outputdir/tmin_queue"
+    local tmin_crashes_dir="$outputdir/tmin_crashes"
+
+    rm -rf "$all_queues_dir" "$cmin_queue_dir" "$tmin_queue_dir" \
+        "$all_crashes_dir" "$cmin_crashes_dir" "$tmin_crashes_dir"
+    mkdir -p "$all_queues_dir" "$cmin_queue_dir" "$tmin_queue_dir" \
+        "$all_crashes_dir" "$cmin_crashes_dir" "$tmin_crashes_dir"
+
+    find "$outputdir"/fuzzer*/queue/ \
+        -maxdepth 1 -type f \
+        -not -iname '*sync*' \
+        -exec cp '{}' "$all_queues_dir/" \;
+    cargo afl cmin \
+        -i "$all_queues_dir" \
+        -o "$cmin_queue_dir" \
+        -m 512 \
+        -- \
+        ./"$fuzz_target"
+    afl_ptmin "$cores" "$cmin_queue_dir" "$tmin_queue_dir" "$fuzz_target"
+
+    find "$outputdir"/fuzzer*/crashes/ \
+        -maxdepth 1 -type f \
+        -not -iname 'README.txt' \
+        -exec cp '{}' "$all_crashes_dir/" \;
+    cargo afl cmin \
+        -C \
+        -i "$all_crashes_dir" \
+        -o "$cmin_crashes_dir" \
+        -m 512 \
+        -- \
+        ./"$fuzz_target"
+    afl_ptmin "$cores" "$cmin_crashes_dir" "$tmin_crashes_dir" "$fuzz_target"
+
+    rm -rf "$all_queues_dir" "$all_crashes_dir" \
+        "$cmin_queue_dir" "$cmin_crashes_dir"
+}
+
+# Helper function to start a number of AFL instances.
+# Args:
+#   $1  the number of AFL instances to be started.
+#   $2  path to the fuzzed binary.
+#   $3  cargo afl fuzz args.
+run_afl_fuzzers() {
+    local cores="$1"
+    local fuzz_target="$2"
+    local cargo_args=("${@:3}")
+
+    for i in $(seq -f "%02g" $cores -1 2); do
+        screen -d -m cargo afl fuzz \
+            -S "fuzzer"$i \
+            "${cargo_args[@]}" \
+            -- \
+            ./$fuzz_target
+    done
+
+    cargo afl fuzz \
+        -M "fuzzer01" \
+        "${cargo_args[@]}" \
+        -- \
+        ./$fuzz_target
+}
+
 # Helper function to run the dev container.
 # Usage: run_devctr <docker args> -- <container args>
 # Example: run_devctr --privileged -- bash -c "echo 'hello world'"
@@ -376,7 +522,7 @@ cmd_help() {
     echo ""
     echo "Available commands:"
     echo ""
-    echo "    build [--debug|--release] [-l|--libc musl|gnu] [-- [<cargo args>]]"
+    echo "    build [--debug|--release] [-l|--libc musl|gnu] [--fuzz afl|stdin] [-- [<cargo args>]]"
     echo "        Build the Firecracker binaries."
     echo "        Firecracker is built using the Rust build system (cargo). All arguments after --"
     echo "        will be passed through to cargo."
@@ -384,6 +530,7 @@ cmd_help() {
     echo "        --release             Build the release binaries."
     echo "        -l, --libc musl|gnu   Choose the libc flavor against which Firecracker will"
     echo "                              be linked. Default is musl."
+    echo "        --fuzz afl|stdin      Build the fuzz targets binaries for the specified fuzz method."
     echo ""
     echo "    fmt"
     echo "        Auto-format all Rust source files, to match the Firecracker requirements."
@@ -418,16 +565,34 @@ cmd_help() {
     echo "    fix_perms"
     echo "        Fixes permissions when devtool dies in the middle of a privileged session."
     echo ""
+    echo "    afl_fuzz [--minimize] [--cores <cores>] <fuzz_target> [-- [<cargo afl fuzz args>]]"
+    echo "        Fuzz the specified target usign AFL."
+    echo "        cargo afl is used to fuzz the target. All arguments after -- will be passed"
+    echo "        through to cargo afl fuzz."
+    echo "        The fuzzer will stop after 5 minutes by default. Use --max_total_time to change"
+    echo "        the fuzzer timeout."
+    echo "        --cores <cores>   Run AFL instances in parallel. Default value is 1."
+    echo "        --minimize        Minimize AFL queue and crashing test cases using afl-cmin and"
+    echo "                          afl-tmin. afl-tmin is parallelized using the number of cores"
+    echo "                          specified by --cores option."
+    echo "        fuzz_target       Fuzz the specified target with AFL. Valid options are: \"block\","
+    echo "                          \"net\", \"vsock\" and \"api_server\"."
+    echo ""
+    echo "    fuzz_coverage <fuzz_target>"
+    echo "        Generate a kcov report by running the fuzz target with AFL generated test cases."
+    echo "        The fuzz target must be compiled for stdin fuzz for coverage"
+    echo "        fuzz_target  The fuzz target which will be used to collect coverage."
+    echo ""
 }
 
-# `$0 build` - build Firecracker
+# `$0 build` - build Firecracker or fuzz targets
 # Please see `$0 help` for more information.
 #
 cmd_build() {
-
     # By default, we'll build the debug binaries.
     profile="debug"
     libc="musl"
+    fuzzing=false
 
     # Parse any command line args.
     while [ $# -gt 0 ]; do
@@ -442,6 +607,13 @@ cmd_build() {
                 libc="$1"
                 ;;
             "--")           { shift; break;         } ;;
+            "--fuzz")
+                shift
+                [[ "$1" =~ ^(stdin|afl)$ ]] || \
+                    die "Invalid fuzzing method: $1. Valid options are \"stdin\" and \"afl\"."
+                fuzzing=true;
+                fuzz_method="$1"
+                ;;
             *)
                 die "Unknown argument: $1. Please use --help for help."
             ;;
@@ -478,16 +650,37 @@ cmd_build() {
     [ $profile = "release" ] && cargo_args+=("--release")
 
     # Run the cargo build process inside the container.
-    # We don't need any special privileges for the build phase, so we run the
-    # container as the current user/group.
-    run_devctr \
-        --user "$(id -u):$(id -g)" \
-        --workdir "$CTR_FC_ROOT_DIR" \
-        -- \
-        cargo build \
-            --target-dir "$CTR_CARGO_TARGET_DIR" \
-            "${cargo_args[@]}"
-    ret=$?
+    if [[ $fuzzing = false ]]; then
+        # We don't need any special privileges for the build phase, so we run the
+        # container as the current user/group.
+        run_devctr \
+            --user "$(id -u):$(id -g)" \
+            --workdir "$CTR_FC_ROOT_DIR" \
+            -- \
+            cargo build \
+                --target-dir "$CTR_CARGO_TARGET_DIR" \
+                "${cargo_args[@]}"
+        ret=$?
+    else
+        cargo_args+=(--features "$fuzz_method""_fuzz")
+        [[ "$fuzz_method" = "stdin" ]] && fuzz_method=""
+
+        docker_cmd="cargo "$fuzz_method" build \
+                        --manifest-path=fuzz/Cargo.toml \
+                        --target-dir "$CTR_CARGO_TARGET_DIR" \
+                        "${cargo_args[@]}""
+
+        run_devctr \
+            --privileged \
+            --ulimit nofile=4096:4096 \
+            --security-opt seccomp=unconfined \
+            --workdir "$CTR_FC_ROOT_DIR" \
+            -- \
+            bash -c "$docker_cmd"
+        ret=$?
+
+        cmd_fix_perms
+    fi
 
     # If `cargo build` was successful, let's copy the binaries to a more
     # accessible location.
@@ -545,6 +738,196 @@ cmd_test() {
     # Running as root would have created some root-owned files under the build
     # dir. Let's fix that.
     cmd_fix_perms
+
+    return $ret
+}
+
+# `$0 afl_fuzz` - run kcov to collect coverage after a fuzzing session
+# Please see `$0 help` for more information.
+#
+cmd_fuzz_coverage() {
+
+     while [ $# -gt 0 ]; do
+        case "$1" in
+            "-h"|"--help")      { cmd_help; exit 1; } ;;
+            "--")               { shift; break;     } ;;
+            --*|-*)
+                die "Unknown argument: $1. Please use --help for help."
+                ;;
+            *)
+                [[ "$1" =~ ^(block|net|vsock|api_server)$ ]] || \
+                    die "Invalid fuzz target: $fuzz_target. Valid options are:" \
+                        "\"block\". \"net\", \"vsock\" and \"api_server\""
+
+                fuzz_target="$1"
+                ;;
+        esac
+        shift
+    done
+
+    [[ -z ${fuzz_target+x} ]] && \
+        die "No fuzz target provided. Valid options are:" \
+            "\"block\". \"net\", \"vsock\" and \"api_server\""
+
+    # Get the relative path to the target binary.
+    fuzz_target_bin="$fuzz_target""_fuzz_target"
+    fuzz_target_bin_rel="$(find "$FC_ROOT_DIR" -executable -type f \
+        -name "$fuzz_target_bin" -printf "%P" -quit 2> /dev/null)"
+
+    [[ -z "$fuzz_target_bin_rel" ]] && \
+        die "Fuzz target binary not found. Please build the target."
+
+    # Find the AFL output dir, prefering the minimized queue dir.
+    if [[ -d "$FC_FUZZ_OUTPUT_DIR/tmin_queue" ]]; then
+        say "Use $FC_FUZZ_OUTPUT_DIR/tmin_queue content as input test cases."
+        inputdir="$CTR_FUZZ_OUTPUT_DIR/tmin_queue"
+    elif [[ -d "$FC_FUZZ_OUTPUT_DIR/fuzzer01/queue" ]]; then
+        say "Use $FC_FUZZ_OUTPUT_DIR/fuzzer01/queue content as input test cases."
+        inputdir="$CTR_FUZZ_OUTPUT_DIR/fuzzer01/queue"
+    else
+        die "Couldn't find input directory. Please "\
+            "create $FC_FUZZ_OUTPUT_DIR/tmin_queue directory."
+    fi
+
+    exclude_pattern=(".cargo/,build/,tests/,usr/lib/gcc")
+    kcov_cmd="kcov $CTR_FUZZ_COVERAGE_DIR --exclude-pattern=$exclude_pattern ./$fuzz_target_bin_rel"
+
+    # Run the target binary for every test case inside container.
+    run_devctr \
+        --privileged \
+        --ulimit nofile=4096:4096 \
+        --security-opt seccomp=unconfined \
+        --workdir "$CTR_FC_ROOT_DIR" \
+        -- \
+        find "$inputdir" \
+            -maxdepth 1 -type f \
+            -exec bash -c "$kcov_cmd < {} && echo \"Coverage for test case {} collected\"" \;
+    ret=$?
+
+    fix_cov_dir_perms
+
+    [[ $ret -eq 0 ]] && {
+        say "Coverage report placed under $FC_FUZZ_COVERAGE_DIR"
+    }
+
+    return $ret
+}
+
+# `$0 afl_fuzz` - fuzz a target using AFL
+# Please see `$0 help` for more information.
+#
+cmd_afl_fuzz() {
+    cores=1
+    minimize=false
+    # Stop de fuzzer after 5 minutes by default.
+    max_total_time=300
+    # Default binary memory limit.
+    mem_limit=512
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            "-h"|"--help")  { cmd_help; exit 1; } ;;
+            "--")           { shift; break;     } ;;
+            "--minimize")   { minimize=true;    } ;;
+            "--cores")
+                shift
+                [[ "$1" =~ ^[0-9]+$ ]] || \
+                    die "Invalid number of cores: $1."
+                cores="$1"
+                ;;
+            --*|-*)
+                die "Unknown argument: $1. Please use --help for help."
+                ;;
+            *)
+                [[ "$1" =~ ^(block|net|vsock|api_server)$ ]] || \
+                    die "Invalid fuzz target: $fuzz_target. Valid options are:" \
+                        "\"block\". \"net\", \"vsock\" and \"api_server\""
+
+                fuzz_target="$1"
+                ;;
+        esac
+        shift
+    done
+
+    [[ -z ${fuzz_target+x} ]] && \
+        die "No fuzz target provided. Valid options are:" \
+            "\"block\". \"net\", \"vsock\" and \"api_server\""
+
+    cargo_args=("$@")
+
+    # Add the default timeout and memory limit if we did not get them in the fuzz command.
+    add_default_timeout=true
+    add_default_mem_limit=true
+    for flag in "${cargo_args[@]}"; do
+        case "$flag" in
+            "--")               { break;                        } ;;
+            --max_total_time=*) { add_default_timeout=false;    } ;;
+            "-m")               { add_default_mem_limit=false;  } ;;
+        esac
+    done
+
+    [[ $add_default_timeout = true ]] && cargo_args+=(--max_total_time="$max_total_time")
+    [[ $add_default_mem_limit = true ]] && cargo_args+=(-m "$mem_limit")
+
+    # Add the default dictionary if one is available.
+    default_dictionary="$(find "$FC_FUZZ_DICTIONARIES_DIR" -type f \
+        -name "$fuzz_target".dict -printf "%P" -quit 2> /dev/null)"
+    [[ -n "$default_dictionary" ]] && \
+        cargo_args+=(-x "$CTR_FUZZ_DICTIONARIES_DIR/$default_dictionary")
+
+    # Add the default input/output dirs.
+    cargo_args+=(-i "$CTR_FUZZ_INPUT_DIR/$fuzz_target")
+    cargo_args+=(-o "$CTR_FUZZ_OUTPUT_DIR")
+
+    # Get the relative path to the target binary.
+    fuzz_target_bin="$fuzz_target""_fuzz_target"
+    fuzz_target_bin_rel="$(find "$FC_ROOT_DIR" -executable -type f \
+        -name "$fuzz_target_bin" -printf "%P" -quit 2> /dev/null)"
+
+    [[ -z "$fuzz_target_bin_rel" ]] && \
+        die "Fuzz target binary not found!"
+
+    # Use run_afl_fuzzers function inside the container to start the
+    # required number of fuzz instances.
+    docker_cmd="$(declare -f run_afl_fuzzers)
+        run_afl_fuzzers $cores $fuzz_target_bin_rel ${cargo_args[@]}"
+
+    run_devctr \
+        --privileged \
+        --ulimit nofile=4096:4096 \
+        --security-opt seccomp=unconfined \
+        --workdir "$CTR_FC_ROOT_DIR" \
+        -- \
+        bash -c "$docker_cmd"
+    ret=$?
+
+    if [[ $ret -eq 0 ]]; then
+        say "Fuzzing session ended successfully."
+        say "Fuzzing output placed under $FC_FUZZ_OUTPUT_DIR."
+
+        if [[ $minimize = true ]]; then
+            # Run the minimizing function inside container.
+            docker_cmd="$(declare -f afl_ptmin)
+            $(declare -f minimize_afl_output)
+            minimize_afl_output $cores $fuzz_target_bin_rel $CTR_FUZZ_OUTPUT_DIR"
+
+            run_devctr \
+                --privileged \
+                --ulimit nofile=4096:4096 \
+                --security-opt seccomp=unconfined \
+                --workdir "$CTR_FC_ROOT_DIR" \
+                -- \
+                bash -c "$docker_cmd"
+            ret=$?
+
+            [[ $ret -eq 0 ]] && {
+                say "Fuzzing output minimization ended successfully."
+                say "Minimized queue and crashes placed under $FC_FUZZ_OUTPUT_DIR."
+            }
+        fi
+    fi
+
+    fix_fuzz_dir_perms
 
     return $ret
 }
